// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdm1vaxtzasKXvN2nMpouVEvhXAKE4HFQ',
    appId: '1:626745613758:web:cde71798ac5a5bb2766def',
    messagingSenderId: '626745613758',
    projectId: 'chatapp-7c8b7',
    authDomain: 'chatapp-7c8b7.firebaseapp.com',
    storageBucket: 'chatapp-7c8b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApHjLGdpm8TUWD0wd2_bBKTTBDhRgOvlo',
    appId: '1:626745613758:android:432217cccf21cfcf766def',
    messagingSenderId: '626745613758',
    projectId: 'chatapp-7c8b7',
    storageBucket: 'chatapp-7c8b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXwyl6r4mdzkYKyoDiuITlY4A1qU_yl-s',
    appId: '1:626745613758:ios:41f47ea865c9cbd2766def',
    messagingSenderId: '626745613758',
    projectId: 'chatapp-7c8b7',
    storageBucket: 'chatapp-7c8b7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXwyl6r4mdzkYKyoDiuITlY4A1qU_yl-s',
    appId: '1:626745613758:ios:41f47ea865c9cbd2766def',
    messagingSenderId: '626745613758',
    projectId: 'chatapp-7c8b7',
    storageBucket: 'chatapp-7c8b7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdm1vaxtzasKXvN2nMpouVEvhXAKE4HFQ',
    appId: '1:626745613758:web:a64725cd491aceea766def',
    messagingSenderId: '626745613758',
    projectId: 'chatapp-7c8b7',
    authDomain: 'chatapp-7c8b7.firebaseapp.com',
    storageBucket: 'chatapp-7c8b7.firebasestorage.app',
  );

}